# Generated by Django 3.0 on 2019-12-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0002_auto_20191215_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_generales',
            name='declaration_tiers',
            field=models.BooleanField(null=True),
        ),
    ]
