# Generated by Django 3.0 on 2019-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0003_auto_20191215_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_generales',
            name='activites_publiees',
            field=models.BooleanField(null=True),
        ),
    ]
