# Generated by Django 3.0 on 2019-12-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0004_auto_20191216_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_generales',
            name='activites_publiees',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info_generales',
            name='declaration_organisation_appartenance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info_generales',
            name='declaration_tiers',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
