# Generated by Django 3.0 on 2019-12-16 14:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('hatvp', '0005_auto_20191216_1047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domaines_interventions',
            new_name='Domaines_intervention',
        ),
        migrations.RenameModel(
            old_name='Info_generales',
            new_name='Informations_generales',
        ),
        migrations.RenameModel(
            old_name='Niveaux_interventions',
            new_name='Niveaux_intervention',
        ),
    ]
