# Generated by Django 3.0 on 2019-12-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0007_auto_20191217_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercices',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='date_premiere_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='derniere_publication_activite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objets_activites',
            name='date_publication_activite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
