# Generated by Django 3.0 on 2019-12-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0010_auto_20191218_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercices',
            name='date_debut',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='date_publication',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
