# Generated by Django 3.0 on 2019-12-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0011_auto_20191218_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercices',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
