# Generated by Django 3.0 on 2019-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0012_auto_20191218_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercices',
            name='date_fin',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='exercices',
            name='exercice_sans_activite',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercices',
            name='nombre_activite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
