# Generated by Django 3.0 on 2019-12-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0014_remove_exercices_nombre_salaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercices',
            name='nombre_salaries',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
