# Generated by Django 3.0 on 2019-12-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0015_auto_20191218_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercices',
            name='nombre_salaries',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
