# Generated by Django 3.0 on 2019-12-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0017_auto_20191218_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions_menees',
            name='other1',
        ),
        migrations.RemoveField(
            model_name='actions_menees',
            name='other2',
        ),
        migrations.RemoveField(
            model_name='actions_menees',
            name='other3',
        ),
        migrations.RemoveField(
            model_name='actions_menees',
            name='other4',
        ),
    ]
