# Generated by Django 3.0 on 2020-01-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0019_auto_20191219_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations_generales',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
