# Generated by Django 3.0 on 2020-01-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0022_auto_20200127_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations_generales',
            name='sigle_HATVP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
