# Generated by Django 3.0 on 2020-01-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0024_auto_20200127_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations_generales',
            name='page_linkedin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
