# Generated by Django 3.0 on 2020-01-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0026_auto_20200127_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliations',
            name='denomination_affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='civilite_collaborateur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dirigeants',
            name='civilite_dirigeant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
