# Generated by Django 3.0 on 2020-01-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0028_auto_20200128_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='observation',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
