# Generated by Django 3.0 on 2020-01-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0029_auto_20200128_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='observation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
