# Generated by Django 3.0 on 2020-01-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0030_auto_20200128_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaires',
            name='beneficiaire_action_menee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
