# Generated by Django 3.0 on 2020-01-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0031_auto_20200128_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions_menees',
            name='action_menee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actions_menees',
            name='action_menee_autre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secteur_activites',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
