# Generated by Django 3.0 on 2020-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0032_auto_20200128_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions_menees',
            name='action_menee',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='actions_menees',
            name='action_menee_autre',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='affiliations',
            name='denomination_affiliation',
            field=models.CharField(blank=True, max_length=145, null=True),
        ),
        migrations.AlterField(
            model_name='affiliations',
            name='identifiant_national_affiliation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='affiliations',
            name='type_identifiant_national_affiliation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaires',
            name='beneficiaire_action_menee',
            field=models.CharField(blank=True, max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='denomination_client',
            field=models.CharField(blank=True, max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='identifiant_national_client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='type_identifiant_national_client',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='civilite_collaborateur',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='fonction_collaborateur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='nom_collaborateur',
            field=models.CharField(blank=True, max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='nom_prenom_collaborateur',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='prenom_collaborateur',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='decisions_concernees',
            name='decision_concernee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dirigeants',
            name='civilite_dirigeant',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='dirigeants',
            name='fonction_dirigeant',
            field=models.CharField(blank=True, max_length=119, null=True),
        ),
        migrations.AlterField(
            model_name='dirigeants',
            name='nom_dirigeant',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='dirigeants',
            name='nom_prenom_dirigeant',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dirigeants',
            name='prenom_dirigeant',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='domaines_intervention',
            name='domaines_intervention_actions_menees',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='chiffre_affaires',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='montant_depense',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='exercices',
            name='nombre_salaries',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='adresse',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='denomination',
            field=models.CharField(blank=True, max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='identifiant_national',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='label_categorie_organisation',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='nom_usage_HATVP',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='page_facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='page_linkedin',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='page_twitter',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='pays',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='sigle_HATVP',
            field=models.CharField(blank=True, max_length=46, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='site_web',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='type_identifiant_national',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='ville',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='niveaux_intervention',
            name='niveau_intervention',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='objets_activites',
            name='identifiant_fiche',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='objets_activites',
            name='objet_activite',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='observation',
            field=models.CharField(blank=True, max_length=710, null=True),
        ),
        migrations.AlterField(
            model_name='secteur_activites',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=59, null=True),
        ),
    ]
