# Generated by Django 3.0 on 2020-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0033_auto_20200128_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='civilite_collaborateur',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='nom_collaborateur',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='nom_prenom_collaborateur',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
