# Generated by Django 3.0 on 2020-01-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0034_auto_20200128_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='prenom_collaborateur',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='sigle_HATVP',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='informations_generales',
            name='ville',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
