# Generated by Django 3.0 on 2020-01-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0035_auto_20200129_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='nom_prenom_collaborateur',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='Ministeres_aai_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_public', models.CharField(blank=True, max_length=210, null=True)),
                ('departement_ministeriel', models.CharField(blank=True, max_length=210, null=True)),
                ('responsable_public_ou_dpt_ministeriel_autre', models.CharField(blank=True, max_length=210, null=True)),
                ('action_representation_interet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatvp.Observations')),
            ],
        ),
    ]
