# Generated by Django 3.0 on 2020-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatvp', '0036_auto_20200130_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministeres_aai_api',
            name='departement_ministeriel',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ministeres_aai_api',
            name='responsable_public',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='ministeres_aai_api',
            name='responsable_public_ou_dpt_ministeriel_autre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
